### ISSUE TITLE
Cannot boot into MacOS

### ISSUE THREAD

**Issue by karlkoala** [RaphMar2021/macOS-t460#2]
Hello there! Sadly Im quite new to this whole hackintosh thing, and I need a system on which I can programm an iOS-app for university. After formatting my USB with RUFUS as stated and putting the EFI folder (which I got from here, newest release) on the drive, I reboot my laptop and select the drive as my boot-medium.  Now I can choose a disc from which to boot or to reset NVRAM. The only two options to boot are my windows partition and my linux partition, I dont have a MacOS option there, but the menu clearly looks like MacOS. If anyone needs more infos I'll gladly provide them! Thank you for the help in advance!

**Comment by RaphMar2021** [comment]
Do you have another folder called "com.apple.recovery" or something like that on your USB pen?

**Comment by karlkoala** [comment]
No, sadly not. I just used RUFUS to delete everything and format the USB in the right way, then I extraced the EFI.7z from this repo onto the USB and after changing my BIOS settings accordingly I tried booting into it. Ive since found out that the reset NVRAM is a common way to solve issues on a real mac. Do you reckon i should try that option? Im really trying to not brick my laptop as there is all my work from uni on there, but if it happens, it happens...

**Comment by RaphMar2021** [comment]
You need to create a macOS recovery image. You can use this tutorial to create one : https://dortania.github.io/OpenCore-Install-Guide/installer-guide/

**Comment by karlkoala** [comment]
Thank you so much! I will try! So I need to use a online installer... ok will try!

**Comment by RaphMar2021** [comment]
No problemo! Hope my EFI will work for you!

**Comment by karlkoala** [comment]
But do I not download a whole version of MacOS from the recovery image? Then I have MacOS, how would I need the EFI if it's already installed? I am not understanding something here, problem of general understanding what EFI files do I think

**Comment by RaphMar2021** [comment]
EFI files is needed to boot macOS. And the image you downloaded is a small image that will download & install macOS

**Comment by karlkoala** [comment]
AH now I get what Im doing. Thank you so much for your help kind sir!

**Comment by RaphMar2021** [comment]
No problem!
