### ISSUE TITLE
random restarts

### ISSUE THREAD

**Issue by nembenike** [RaphMar2021/macOS-t460#4]
I get fully random restarts in Ventura, usually happens while watching YouTube videos

**Comment by RaphMar2021** [comment]
Hi, sorry for the delay: i'm not really active on this repo.

It's maybe due to the GPU, since macOS dropped the support for Intel Skylake (i5-6XXX) GPUs?

But, please give some more infos, such as the latest file you could find in the '/Library/Logs/DiagnosticReports' folder.

**Comment by nembenike** [comment]
I don't have it anymore but do any of the other versions support those GPUs?

**Comment by RaphMar2021** [comment]
> I don't have it anymore but do any of the other versions support those GPUs?

@nembenike You may try to use version 1.1 with macOS Monterey. It's more stable and the Skylake GPU is supported officially on this version.

**Comment by nembenike** [comment]
Okay thanks.

**Comment by RaphMar2021** [comment]
No problem :)
